general {
        output_format = "i3bar"
        colors = true
        interval = 5
}

order += "disk /"
order += "disk /home/aschey"
order += "wireless wlp2s0"
order += "battery 0"
order += "cpu_temperature 0"
order += "cpu_temperature 1"
order += "cpu_temperature 2"
order += "cpu_temperature 3"
order += "cpu_usage"
order += "load"
order += "time"

wireless wlp2s0 {
        format_up = "W: (%quality at %essid, %bitrate) %ip"
        format_down = "W: down"
}


battery 0 {
        format = "%status %percentage %remaining %emptytime"
        path = "/sys/class/power_supply/BAT%d/uevent"
}

load {
        format = "%5min"
}

cpu_temperature 0 {
        format = "T0: %degrees °C"
        path = "/sys/devices/platform/coretemp.0/hwmon/hwmon0/temp1_input"
}

cpu_temperature 1 {
        format = "T1: %degrees °C"
        path = "/sys/devices/platform/coretemp.0/hwmon/hwmon0/temp2_input"
}

cpu_temperature 2 {
        format = "T2: %degrees °C"
        path = "/sys/devices/platform/coretemp.0/hwmon/hwmon0/temp3_input"
}

cpu_temperature 3 {
        format = "T3: %degrees °C"
        path = "/sys/devices/platform/coretemp.0/hwmon/hwmon0/temp4_input"
}

cpu_usage {
    format = "%usage"
}

disk "/" {
        format = "root: %free / %total"
}

disk "/home/aschey" {
        format = "home: %free / %total"
}

time {
        format = "%m-%d %H:%M:%S"
}
